# Generated by Django 2.1 on 2019-11-12 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_x', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='eth_add',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='records',
            name='eth_private_key',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
