# Generated by Django 2.1 on 2019-11-12 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_x', '0002_auto_20191113_0138'),
    ]

    operations = [
        migrations.AddField(
            model_name='records',
            name='image',
            field=models.FileField(blank=True, upload_to='C:\\Users\\Sumit\\Documents\\Django\\project_x/pic'),
        ),
    ]
