# Generated by Django 2.1 on 2019-11-14 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_x', '0003_records_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='records',
            old_name='image',
            new_name='Image',
        ),
    ]
